apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpesview-deployment

#ESPECIFICAÇÃO DAS REPLICAS
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpesview-pod

  #ESPECIFICAÇÃO DO POD
  template:
    metadata:
      labels:
        app: cpesview-pod
    spec:
      imagePullSecrets:
        - name: docker-registry-ssp
      containers:
        - name: cpesview-container
          image: docker.ssp.go.gov.br/ssp/cpesview:{{COMMIT_ID}}
          readinessProbe:
            httpGet:
              path: /
              port: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
